variables:
  DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE_DEV: libcimpp-dev
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - prepare
  - build-src
  - build-doc
  - deploy

docker:
  stage: prepare
  script:
    - docker build -t ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV} .
    - docker images
  tags:
    - shell

# Template
.build-src: &build-src
  stage: build-src
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  tags:
    - docker
  script:
    - mkdir -p build/${CIM_VERSION} && cd build/${CIM_VERSION}
    - cmake ../.. -DUSE_CIM_VERSION=${CIM_VERSION}
    - make -j8

build-src-CGMES:
  <<: *build-src
  variables:
    CIM_VERSION: IEC61970_CGMES

build-src-16v29a:
  <<: *build-src
  variables:
    CIM_VERSION: IEC61970_16v29a

build-src-17v07:
  <<: *build-src
  variables:
    CIM_VERSION: IEC61970_17v07

build-src-16v29a-12v08:
  <<: *build-src
  variables:
    CIM_VERSION: IEC61970_16v29a_IEC61968_12v08

build-src-16v29a-sinergien:
  <<: *build-src
  variables:
    CIM_VERSION: IEC61970_16v29a_SINERGIEN

# Documentation
.build-doc: &build-doc
  stage: build-doc
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  tags:
    - docker
  script:
    - mkdir -p build/${CIM_VERSION} && cd build/${CIM_VERSION}
    - cmake ../.. -DUSE_CIM_VERSION=${CIM_VERSION}
    - make doc
  artifacts:
    paths:
      - build/${CIM_VERSION}/doc/html
    expire_in: 6 months

build-doc-16v29a:
  <<: *build-doc
  variables:
    CIM_VERSION: IEC61970_16v29a

build-doc-17v07:
  <<: *build-doc
  variables:
    CIM_VERSION: IEC61970_17v07

build-doc-16v29a-12v08:
  <<: *build-doc
  variables:
    CIM_VERSION: IEC61970_16v29a_IEC61968_12v08

build-doc-16v29a-sinergien:
  <<: *build-doc
  variables:
    CIM_VERSION: IEC61970_16v29a_SINERGIEN
